services:
  hondabot:
    build: .
    container_name: HondaBot
    restart: always
    volumes:
      - ./credentials:/app/credentials
      - ./instances:/app/instances
      - ./logs:/app/logs
      - ./maps:/app/maps
    environment:
      - RPP_DISCORD_CLIENT_ID=${RPP_DISCORD_CLIENT_ID}
      - RPP_DISCORD_TOKEN=${RPP_DISCORD_TOKEN}
      - RPP_DISCORD_USERNAME=${RPP_DISCORD_USERNAME}
    mem_limit: 600m
    cpus: 0.8

